### ISSUE TITLE
Does it possible to create some checkboxes for multiple choices?

### ISSUE THREAD

**Issue by Jimmortal** [hypnospinner/MIAC-reports#5]
Checkboxes control multiple condition for each string or for everything.
For example:
Admin checks main box - BLOCKS ALL TABS - noone can use tabs.
Admin checks several boxes on strings - several users can use reporting/

![ch3ckbox3s](https://user-images.githubusercontent.com/6452425/58862224-df4d4b80-86b8-11e9-8432-bb6afa8825ce.png)

**Comment by hypnospinner** [comment]
Closed as it's not needed more
